### ISSUE TITLE
Can't call constructor with no parameters

### ISSUE THREAD

**Issue by snoretrain** [bytetechnology/winston-gelf-transporter#3]
The docs specify being able to use the transporter with no args, but calling the constructor with no args gives an error. Doing:
`const winstonGelfTransporter = new WinstonGelfTransporter();`
results in:
`TypeError: Cannot read property 'protocol' of undefined` 

As you can see here in the source
https://github.com/bytetechnology/winston-gelf-transporter/blob/63f61b47b67662ec8ac8ebf8aedc9a344530c29a/src/WinstonGelfTransporter.ts#L46
there is an expectation that options is a non null TransporterOptions object.

**Comment by snoretrain** [comment]
To resolve this, we will want to add the ability to do:

`const winstonGelfTransporter = new WinstonGelfTransporter();`

with the result being the same as if the options were:

```
  level: null
  silent: false;
  handleExceptions: false;
  version: '1.1';
  host: 'graylog';
  port: 12201;
  protocol: 'udp';
  hostName: os.hostname();
  additional: {};
```

**Comment by ujwal-setlur** [comment]
Can’t you you just have defaults?

```js 

constructor(options?: TransporterOptions = {
protocol: ‘udp’,
...
}) {

```

**Comment by snoretrain** [comment]
@ujwal-setlur yeah, that's a pretty straightforward way to solve it, originally I thought it might be a little messy to look at but that's why we have indentation and highlighting isn't it 😂
